name: qr4all
description: "A somewhat redundant project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.0
  share_plus: ^11.0.0
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  shared_preferences_web: ^2.4.3
  universal_html: ^2.2.4
  audioplayers: ^6.4.0
  android_intent_plus: ^5.3.0
  camera: ^0.11.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/sounds/beep.mp3
  uses-material-design: true
